Feature/dynamic backgrounds
lisalootens/personal-website pull request #59
Opened 2023-12-11 11:16 UTC by lisalootens

2023-12-11 11:38 UTC, jobveldhuis requested changes

2023-12-11 11:38 UTC, jobveldhuis commented on src/components/backgrounds/Background.tsx
> +  switch (true) {
Please don't switch over true - it's a code smell. In this case, it would be best to:

```tsx
export function Background() {
  if (isBirthdayBackgroundInRange) return <BirthdayBackground />;
  if (isSnowBackgroundInRange) return <SnowBackground />;
  return <CirclesBackground />
```

In this case, you wouldn't even need to check whether the birthday background is in range for the snow background, because of the pattern of an early exit when this is the case.

2023-12-11 11:38 UTC, jobveldhuis commented on src/components/backgrounds/Background.tsx
> +const isSnowBackgroundInRange =
Semantically, you would prefer to make this a boolean comparison, not a ternary operation - since this really isn't a choice between two. Instead, it's a scenario of (A and B), leading to the following:

```ts
const isSnowBackgroundInRange = !isBirthdayBackgroundInRange && (currentMonth >= 11 || currrentMonth <= 2);
```

Also, depending on the structure of the code that renders, you might not need this initial check before the `&&`. See my comment below.

2023-12-11 11:38 UTC, jobveldhuis commented on src/components/backgrounds/Background.tsx
> +const isSnowBackgroundInRange =
Naming variables is hard, but I would say you should reconsider naming these two variables. For example, something like:

```ts
const isBirthdayClose = true;
const isWinter = true;
```

Which would more clearly convey the meaning of the right hand side of these assignments.

2023-12-11 11:38 UTC, jobveldhuis commented on src/components/backgrounds/SnowBackground.tsx
> +function getRandomInt(min: number, max: number) {
What does `getRandomInt` return? Of course, we know this returns a random integer, but why not type it this way as well. This would help the compiler step through your code more quickly, also it will catch any unwanted bugs in the future if you're a bit more specific here.

2023-12-11 11:38 UTC, jobveldhuis commented on src/components/backgrounds/SnowBackground.tsx
> +          // Generate random values within specified ranges
This should probably be a component, you're doing a lot of calculations here - which should only exist in the component. For example a `SnowFlake` component, or whatever. This could internally calculate and then render to this screen.

2023-12-14 08:03 UTC, lisalootens commented on src/components/backgrounds/SnowBackground.tsx
> +function getRandomInt(min: number, max: number) {
Sorry, I don't quite get what you mean.

2023-12-14 08:10 UTC, lisalootens commented on src/components/backgrounds/SnowBackground.tsx
> +          // Generate random values within specified ranges
Agreed - lots of calculations and this might not really fit here, but don't you want to keep these sort of things within the component? Does it really need to be a separate component?

2023-12-15 09:22 UTC, jobveldhuis commented on src/components/backgrounds/SnowBackground.tsx
> +function getRandomInt(min: number, max: number) {
If you add a return type, you can help the compiler and type checker a bit with these kind of functions. It's good practice to not always do this, because sometimes you *want* to infer the return type based on the function return statements, but when you don't and you are sure what it should return, it's good practice to add a return type.

```ts
function getRandomInt(min: number, max: number): number {
    ...
}
```

Say you update this function without adding a return type:
```ts
// Stupid code for demonstration purposes only
function getRandomInt(min: number, max: number) {
  return Math.random() > 0.5 ? 1 : "Test"
}
```

This would be perfectly valid and all your code that depends on it now is "broken". For everywhere you call this function, the variable attached will be of type `string | number` and in bigger code bases this may lead to an absolute nightmare of recovery work if you don't identify the source of this issue quickly. If you add a return type, however, and you do the same change - the TS compiler will error out on *this function and this function only*, so you have identified the source without having to do anything.

TL:DR - Add return types when you know what functions should return and you don't want to infer a return type based on returns in the function body.

2023-12-15 09:22 UTC, jobveldhuis commented on src/components/backgrounds/SnowBackground.tsx
> +          // Generate random values within specified ranges
The way I see it, components are functions and functions should do one thing and one thing only. In this case, you want to have a component that renders the wrapper around the snowflakes and you want to have the snowflakes themselves. These are two separate components, because they do two vastly different things. Where you add this component is up to you: either in a separate file or in this file. I try to stick to the "one component per file" rule where possible, because it makes codebases more readable.

2023-12-18 10:29 UTC, merged